---
title: "WebApp"
author: "Mishi Makade & Palesa Baisetse"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Importing libraries

```{r}
library(shiny)
library(data.table)
library(shinydashboard)
library(e1071)
library(tidytext)
library(dplyr)
library(keras)
library(ggplot2)
library(tm)
library(textclean)
library(syuzhet)
library(lubridate)
library(reshape2)
library(caret)
library(RCurl)
library(OpenImageR)
library(magick)
library(pdftools)
library(tidyverse)
library(magick)
library(pdftools)
library(tesseract)
```

# Source

```{r}
source("C:/Users/Student/Desktop/Fol/3rd Year 2ND Semester/DataScience2B/Project/Assignment/RealSources.R")
```


## Read in the model


```{r }
model=readRDS("Random_Forest_Final_model.rds")
```

# **Web Application**




```{r warning=FALSE}
library(magick)
ui=fluidPage(
  
  dashboardPage(
    dashboardHeader(title = "Sucide Detection"),
    
    dashboardSidebar(width = 160,
                     
                     sidebarMenu(style = "position: fixed; width:150px;",
                                 
                    fileInput("file1","Upload your txt file",accept = ".txt"),
                    
                    fileInput("file2","Upload your image file",accept =c('.png','.jpeg','.jpg'))
                    
                     )
                    
),
  dashboardBody(
    
   tabsetPanel(type = "tabs",
    tabPanel("Help",imageOutput("helpimage")),
    tabPanel("Prediction",
             tags$label(h3('Status/Output')),
             verbatimTextOutput('contents'),
              tableOutput('tabledata') ,#prediction results table
              actionButton("submitbutton",
                 "Submit",
                 class="btn btn-primary")),

     tabPanel("Kimberly Suicide Prevention Helplines",imageOutput("tabimage"))
            
   ))
)
)




## Server

server=function(input,output,session){
  
text_data=reactive({


    
      data1 <- input$file1
      data2=input$file2
      
      
      
      if(!is.null(data2))
      {

        im=magick::image_read(req(input$file2$datapath))

        text=OCR(im)
        
      }
      
      else if(!is.null(data1))
      {
        text=read.table(
        data1$datapath,sep = "\n",col.names = c("Text"))
      }
        


      
      user_data=model_user_input(text)
      
      Output=as.data.frame(predict(model,newdata=user_data,type = "prob"))

      colnames(Output)=c("Non-Suicidal","Suicidal")
      
      Output=cbind(Output,text)
      
      
      print(Output)
})
    

      
      
      # Status/Output Text Box
      
      output$contents=renderPrint(
        {
          if(input$submitbutton>0)
          {
            isolate("Calculation Complete")
          }
          else
          {
            return("Server is ready for classifying")
          }
        }
      )
      
      # Prediction results table
      
      output$tabledata=renderTable(
        {
          if(input$submitbutton>0)
          {
            isolate(text_data())
          }
        }
      )
      
       output$contents <- renderPrint({
    if (input$submitbutton>0) { 
      isolate("Calculation complete.") 
    } else {
      return("Server is ready for calculation.")
    }
  })
      
      tabfilename=normalizePath(file.path("C:/Users/Student/Desktop/Fol/3rd Year 2ND Semester/DataScience2B/Project/Assignment/SuicidePreventionImage.png"))
      
          output$tabimage<-renderImage({
  list(src = tabfilename,
       contentType = 'image/png',
       alt = "This is alternate text")
}, deleteFile = FALSE)
          
          
          
      filnam=normalizePath(file.path("C:/Users/Student/Desktop/Fol/3rd Year 2ND Semester/DataScience2B/Project/Assignment/Help.png"))
      
          output$helpimage<-renderImage({
  list(src = filnam,
       contentType = 'image/png',
       alt = "This is alternate text")
}, deleteFile = FALSE)
      
      
    }
  
    
  
  
  
  # Create the shiny app
shinyApp(ui=ui,server=server)    
```





